config/routes.rb
Rails.application.routes.draw do

  devise_for :customer,
    path: :customers,
    :controllers => {
      :registrations => "customer/registrations",
      :sessions => "customer/sessions",
      :passwords => "customer/passwords"
    }

  devise_for :admin,
    path: :admins,
    :controllers => {
      :sessions => "admin/sessions"
    }

  get "/" => "customer/items#top", as: "top"
  get "/about" => "customer/items#about", as: "about"
  get "/customers" => "customer/customers#rule", as: "customer_rule"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin, path: :admins do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :item_orders, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    get "orders/current_user_order/:id" => "orders#current_user_order"
  end

  namespace :customer, path: :customers do
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :create, :destroy]
    delete "cart_items" => "cart_items#all_destroy", as: "cart_item_all_destroy"


    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post "confirm"
        get "complete"
      end
    end

    resources :deliver_destinations, only: [:index, :create, :destroy, :edit, :update]
    get "my_page" => "customers#show", as: "customer"
    get "leave" => "customers#leave", as: "customer_leave"
    patch "out" => "customers#out", as: "customer_out"
    get "edit/my_page" => "customers#edit", as: "customer_edit"
    patch "update" => "customers#update", as: "customer_update"
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :orders, dependent: :destroy

  #フルネームメソッド
  def full_name
    self.last_name + self.first_name
  end

  #フルネームカナメソッド
  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end


  has_many :deliver_destinations, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postcode, presence: true, numericality: { only_integer: true }, length: { is: 7 }
  validates :address, presence: true
  validates :phone, presence: true, numericality: { only_integer: true }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :customer_shut_out


  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    render action: :show
  end

  private
   def customer_params
     params.require(:customer).permit(
       :email,
       :first_name,
       :last_name,
       :first_name_kana,
       :last_name_kana,
       :postcode,
       :address,
       :phone,
       :is_deleted
       )end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_customer!
  before_action :baria_user, only: [:update, :destroy]

  def index
    @cart_items = current_customer.cart_items
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(quantity: params[:cart_item][:quantity].to_i)
    flash[:notice] = "#{@cart_item.item.name}の数量を変更しました。"
    redirect_to customer_cart_items_path
  end

  def create
    @cart_item = current_customer.cart_items.new(params_cart_item)
    @update_cart_item = CartItem.find_by(item: @cart_item.item)
    if @update_cart_item.present? && @cart_item.valid?
      @cart_item.quantity += @update_cart_item.quantity
      @update_cart_item.destroy
    end
    if @cart_item.save
      flash[:notice] = "#{@cart_item.item.name}をカートに追加しました。"
      redirect_to customer_cart_items_path
    else
      @item = Item.find(params[:cart_item][:item_id])
      @cart_item = CartItem.new
      flash[:alert] = "個数を選択してください。"
      render "customer/items/show"
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:alert] = "#{@cart_item.item.name}を削除しました。"
    redirect_to customer_cart_items_path
  end

  def all_destroy
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    flash[:alert] = "カートの商品を全て削除しました。"
    redirect_to customer_cart_items_path
  end

  private

  def params_cart_item
    params.require(:cart_item).permit(:quantity, :item_id)
  end

  def baria_user
    unless CartItem.find(params[:id]).customer.id.to_i == current_customer.id
      redirect_to customer_customer_path
    end
  end

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!, only: [:show, :leave, :out, :edit, :update]
  before_action :rule_path, only: [:rule]

  def show
    @customer = current_customer
  end

  def leave
    @customer = current_customer
  end

  def out
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    flash[:alert] = "退会処理が完了しました。"
    redirect_to top_path
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を更新しました。"
      redirect_to customer_customer_path
    else
      render :edit
    end
  end

  def rule
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone, :email)
  end

  def rule_path
    unless customer_signed_in?
      redirect_to new_customer_registration_path
    end
  end

end

app/controllers/customer/deliver_destinations_controller.rb
class Customer::DeliverDestinationsController < ApplicationController
  before_action :authenticate_customer!
  before_action :baria_user, only: [:destroy, :edit, :update]

  def index
    @deliver_destination = DeliverDestination.new
    @deliver_destinations = current_customer.deliver_destinations
  end

  def create
    @deliver_destination = DeliverDestination.new(deliver_destination_params)
    @deliver_destination.customer_id = current_customer.id
    @deliver_destinations = current_customer.deliver_destinations
    if @deliver_destination.save
      flash[:notice] = "配送先を登録しました。"
      redirect_to customer_deliver_destinations_path
    else
      render :index
    end
  end

  def destroy
    @deliver_destination = DeliverDestination.find(params[:id])
    @deliver_destination.destroy
    flash[:alert] = "配送先を削除しました。"
    redirect_to customer_deliver_destinations_path
  end

  def edit
    @deliver_destination = DeliverDestination.find(params[:id])
  end

  def update
    @deliver_destination = DeliverDestination.find(params[:id])
    if @deliver_destination.update(deliver_destination_params)
      flash[:notice] = "配送先情報を変更しました。"
      redirect_to customer_deliver_destinations_path
    else
      render :edit
    end
  end

  private

  def deliver_destination_params
    params.require(:deliver_destination).permit(:postcode, :address, :destination)
  end

  def baria_user
    unless DeliverDestination.find(params[:id]).customer.id.to_i == current_customer.id
      redirect_to customer_customer_path
    end
  end

end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  include ApplicationHelper

  def index
    @items = Item.all.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  def about
  end

  def top
    @items = Item.all
  end

end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  include ApplicationHelper

  before_action :to_confirm, only: [:show]
  before_action :authenticate_customer!

  def new
    @order = Order.new
    @deliver_destinations = DeliverDestination.where(customer: current_customer)
  end

  def confirm
    @cart_items = current_customer.cart_items
    @order = Order.new

    @order.tax_price = billing(@order)

     if params[:order][:addresses] == "residence"
      @order.postcode = current_customer.postcode
      @order.address = current_customer.address
      @order.destination = current_customer.last_name + current_customer.first_name
     elsif params[:order][:addresses] == "registration"
      delivery = DeliverDestination.find(params[:order][:deliver_destination_id])
      @order.postcode = delivery.postcode
      @order.address = delivery.address
      @order.destination = delivery.destination
     elsif params[:order][:addresses] == "new_address"
      @order.postcode = params[:order][:postcode]
      @order.address = params[:order][:address]
      @order.destination = params[:order][:destination]
      @delivery = "1"
     end
  end

  def create
    @order = current_customer.orders.new(order_params)
    @order.save
    flash[:notice] = "ご注文が確定しました。"
    redirect_to complete_customer_orders_path

    if params[:order][:delivery] == "1"
      current_customer.deliver_destinations.create(address_params)
    end

    @cart_items = current_customer.cart_items
    @cart_items.each do |cart_item|
    ItemOrder.create(
      item: cart_item.item,
      order: @order,
      quantity: cart_item.quantity,
      tax_price: tax_price(cart_item.item.price)
      )
    end

     @cart_items.destroy_all
  end

  def complete
  end

  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @item_orders = @order.item_orders
  end

  private
  def order_params
    params.require(:order).permit(:tax_price, :payment, :postcode, :address, :destination)
  end

  def address_params
    params.require(:order).permit(:postcode, :address, :destination)
  end

  def to_confirm
    redirect_to customer_items_path if params[:id] == "confirm"
  end

end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  before_action :reject_inactive_user, only: [:create]

  private

  def reject_inactive_user
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && @customer.is_deleted
        flash[:alert] = "退会済のアカウントです。ご利用いただけません。"
        redirect_to new_customer_session_path
      end
    end
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/deliver_destinations_helper.rb
module Customer::DeliverDestinationsHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/customer/customers/edit.html.erb
<div class="container-xxl mt-5 mx-5">

  <h2><mark>会員情報編集</mark></h2>

  <div class="customer-edit row mt-5" style="margin-left: 0; margin-right: 0; padding-left: 0;">
    <%= form_with model: @customer, url: customer_customer_update_path, class: "col-12", local: true do |f| %>
      <%= render "customer/shared/error_messages_customer_edit", model: f.object %>
      <%= f.label "名前", class: "col-2 mr-3" %>
      <%= f.text_field :last_name, autocomplete: "last_name", class: "col-2 mr-3" %>
      <%= f.text_field :first_name, autocomplete: "first_name", class: "col-2" %>
      <div class="w-100"></div>
      <%= f.label "フリガナ", class: "col-2 mr-3" %>
      <%= f.text_field :last_name_kana, autocomplete: "last_name_kana", class: "col-2 mr-3" %>
      <%= f.text_field :first_name_kana, autocomplete: "first_name_kana", class: "col-2" %>
      <div class="w-100"></div>
      <%= f.label "郵便番号", class: "col-2 mr-3" %>
      <%= f.text_field :postcode, autocomplete: "postcode", class: "col-2"  %>
      <div class="w-100"></div>
      <%= f.label "住所", class: "col-2 mr-3" %>
      <%= f.text_field :address, autocomplete: "address", class: "col-5" %>
      <div class="w-100"></div>
      <%= f.label "電話番号", class: "col-2 mr-3" %>
      <%= f.text_field :phone, autocomplete: "phone", class: "col-2" %>
      <div class="w-100"></div>
      <%= f.label "メールアドレス", class: "col-2 mr-3" %>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "col-2" %>
      <div class="actions mt-4 text-center">
        <%= f.submit "編集内容を保存", class: "btn btn-success mr-5" %>
        <%= link_to "退会する", customer_customer_leave_path, class: "btn btn-danger ml-5" %>
      </div>
    <% end %>
  </div>
</div>

app/views/customer/customers/leave.html.erb
<div class="customer-leave container px-5 px-md-0 text-center">

  <h3><strong>本当に退会しますか？</strong></h3>

  <p class="mt-5">
    退会すると、会員登録情報や<br />
    これまでの購入履歴が閲覧できなくなります。<br />
    退会する場合は、「退会する」をクリックしてください。
  </p>

  <div class="mt-5">
    <%= link_to "退会しない", customer_customer_path, class: "btn btn-primary mr-5" %>
    <%= link_to "退会する", customer_customer_out_path, method: :patch, class: "btn btn-danger" %>
  </div>
</div>

app/views/customer/customers/rule.html.erb
<div class="container-xxl mt-5 mx-5">

  <h2><mark>会員のみなさまへ</mark></h2>

  <h3 class="mt-5">[ご注文から発送までの流れ]</h3>

  <p class="mt-4">
    ご希望の商品、数量(商品1種類あたり10点まで)を選択し、注文画面にてお支払方法、配送先をご指定下さい。<br />
    送料は全国一律800円(税込)となっております。<br />
  </p>

  <p>
    当店は完全受注生産とさせていただいております。<br />
    ご注文完了後、入金が確認出来次第制作を開始し、通常1〜2営業日で発送いたします。<br />
    (ご購入数量が多い場合、またはクリスマス等の繁忙期では発送まで3営業日以上をいただく場合がございます。)
  </p>

</div>

app/views/customer/customers/show.html.erb
<div class="container-xxl mt-5 mx-5">

  <h2><mark>マイページ</mark></h2>

  <div class="customer-information mt-5">
    <div class="row" style="margin-left: 0; margin-right: 0;">
      <h4 class="d-flex align-items-center justify-content-center" style="margin-bottom: 0;"><strong>登録情報</strong></h4>
      <%= link_to "編集する", customer_customer_edit_path, class: "btn btn-success ml-5" %>
    </div>
    <table class="col-6 table table-bordered mt-3 mb-5">
      <tr>
        <td class="table-active border border-dark">氏名</td>
        <td class="border border-dark"><%= @customer.last_name %> <%= @customer.first_name %></td>
      </tr>
      <tr>
        <td class="table-active border border-dark">カナ</td>
        <td class="border border-dark"><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td class="table-active border border-dark">郵便番号</td>
        <td class="border border-dark"><%= @customer.postcode %></td>
      </tr>
      <tr>
        <td class="table-active border border-dark">住所</td>
        <td class="border border-dark"><%= @customer.address %></td>
      </tr>
      <tr>
        <td class="table-active border border-dark">電話番号</td>
        <td class="border border-dark"><%= @customer.phone %></td>
      </tr>
      <tr>
        <td class="table-active border border-dark">メールアドレス</td>
        <td class="border border-dark"><%= @customer.email %></td>
      </tr>
    </table>

    <div class="row col-2" style="margin-left: 0; margin-right: 0; padding-left: 0;">
      <h4 class="col-6 d-flex align-items-center justify-content-left" style="margin-bottom: 0; padding-left: 0;"><strong>配送先</strong></h4>
      <%= link_to "一覧を見る", customer_deliver_destinations_path, class: "col-6 btn btn-primary" %>
      <div class="w-100 mt-4"></div>
      <h4 class="col-6 d-flex align-items-center justify-content-left" style="margin-bottom: 0; padding-left: 0;"><strong>注文履歴</strong></h4>
      <%= link_to "一覧を見る", customer_orders_path, class: "col-6 btn btn-primary" %>
    </div>

  </div>
</div>