config/routes.rb
Rails.application.routes.draw do

  devise_for :customer,
    path: :customers,
    :controllers => {
      :registrations => "customer/registrations",
      :sessions => "customer/sessions",
      :passwords => "customer/passwords"
    }

  devise_for :admin,
    path: :admins,
    :controllers => {
      :sessions => "admin/sessions"
    }

  get "/" => "customer/items#top", as: "top"
  get "/about" => "customer/items#about", as: "about"
  get "/customers" => "customer/customers#rule", as: "customer_rule"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin, path: :admins do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :item_orders, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    get "orders/current_user_order/:id" => "orders#current_user_order"
  end

  namespace :customer, path: :customers do
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :create, :destroy]
    delete "cart_items" => "cart_items#all_destroy", as: "cart_item_all_destroy"


    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post "confirm"
        get "complete"
      end
    end

    resources :deliver_destinations, only: [:index, :create, :destroy, :edit, :update]
    get "my_page" => "customers#show", as: "customer"
    get "leave" => "customers#leave", as: "customer_leave"
    patch "out" => "customers#out", as: "customer_out"
    get "edit/my_page" => "customers#edit", as: "customer_edit"
    patch "update" => "customers#update", as: "customer_update"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord


  belongs_to :customer
  belongs_to :item

  validates :quantity, numericality: { only_integer: true }


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :orders, dependent: :destroy

  #フルネームメソッド
  def full_name
    self.last_name + self.first_name
  end

  #フルネームカナメソッド
  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end


  has_many :deliver_destinations, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postcode, presence: true, numericality: { only_integer: true }, length: { is: 7 }
  validates :address, presence: true
  validates :phone, presence: true, numericality: { only_integer: true }

end

app/models/deliver_destination.rb
class DeliverDestination < ApplicationRecord
  belongs_to :customer

  validates :postcode, presence: true, numericality: { only_integer: true }, length: { is: 7 }
  validates :address, presence: true
  validates :destination, presence: true

	# order/newで使用
  def order_address
	self.postcode + self.address + self.destination
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord


  validates :genre_id, :name, :price, presence: true
  validates :introduction, length: {maximum: 200}
  validates :price, numericality: { only_integer: true }

  attachment :image
  belongs_to :genre

  has_many :item_orders, dependent: :destroy

  has_many :cart_items, dependent: :destroy

end

app/models/item_order.rb
class ItemOrder < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum maiking_status: { 製作不可: 0, 製作待ち: 1, 製作中: 3, 製作完了: 4 }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :item_orders, dependent: :destroy

    #注文の全ての数量合計
  def sum_order_items
    self.item_orders.all.sum(:quantity)
  end

  #注文の合計金額
  def total_price
    array = []
    self.item_orders.each do |item_order|
       array << item_order.tax_price * item_order.quantity
   end
    array.sum
  end

  enum payment: { クレジットカード: 0, 銀行振込: 1}
  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}



  validates :customer_id, :address,:destination, :postage, :payment, :tax_price, presence: true
	validates :postcode, length: {is: 7}, numericality: { only_integer: true }
	validates :postage, :tax_price, numericality: { only_integer: true }



end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :customer_shut_out

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
       flash[:notice] = "You have created Item successfully"
       redirect_to admin_item_path(@item.id)
    else
       render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       flash[:notice] = "You have update Item successfully"
       redirect_to admin_item_path(@item.id)
    else
       render :edit
    end
  end

private

def item_params
  params.require(:item).permit(:genre_id, :name, :introduction, :price, :image, :is_active)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :address, :phone, :is_deleted])
  end

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_items_path
    else
      top_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      new_customer_session_path
    end
  end

  def customer_shut_out
    unless admin_signed_in?
      redirect_to top_path
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/item_orders_helper.rb
module Admin::ItemOrdersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tax_price(price)
    (price * 1.1).floor
  end

  def sub_price(sub)
    (tax_price(sub.item.price) * sub.quantity)
  end

  def total_price(totals)
    price = 0
    totals.each do |total|
      price += sub_price(total)
    end
    return price
  end

  def current_cart
    @cart_items = current_customer.cart_items
  end

  def billing(order)
    total_price(current_cart) + order.postage
  end

end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <span>Nagano Cake</span>
          </a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <li class="customer-name">
                  ようこそ、<%= current_customer.last_name %> さん
                </li>
                <li class="ml-4">
                  <%= link_to "会員のみなさまへ", customer_rule_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="ml-4">
                  <%= link_to "マイページ", customer_customer_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="ml-4">
                  <%= link_to "商品一覧", customer_items_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="ml-4">
                  <%= link_to "カート", customer_cart_items_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="ml-4 mr-4">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark" %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="ml-4">
                  <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="ml-4">
                  <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="ml-4">
                  <%= link_to "注文履歴一覧", admin_orders_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="ml-4">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="ml-4 mr-4">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark" %>
                </li>
              <% else %>
                <li class="ml-4">
                  <%= link_to "About", about_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="ml-4">
                  <%= link_to "商品一覧", customer_items_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="ml-4">
                  <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="ml-4 mr-4">
                  <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-dark" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

    </header>

    <main>
      <div id="flash-sentence">
        <% if flash[:notice] %>
          <p class="notice"><%= flash[:notice] %></p>
        <% else %>
          <p class="alert"><%= flash[:alert] %></p>
        <% end %>
      </div>

      <%= yield %>
    </main>
  </body>
</html>